swagger: '2.0'
x-interface-model: cluster
x-endpoint-name: dw
x-releases: DW,SDX
info:
  version: 0.1-SNAPSHOT
  title: Cloudera Data Warehouse
  license:
    name: Apache 2.0
  description: Cloudera Data Warehouse is a service that makes it easy to analyze large amounts of data efficiently.
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /dw/createCluster:
    post:
      summary: Creates a new cluster.
      description: Creates a new cluster.
      operationId: createCluster
      x-entitlement: DW
      parameters:
        - name: input
          in: body
          required: true
          schema:
            $ref: '#/definitions/CreateClusterRequest'
      responses:
        200:
          description: Expected response to a valid request.
          schema:
            $ref: '#/definitions/CreateClusterResponse'
        default:
          description: The default response on an error.
          schema:
            $ref: '#/definitions/Error'
  /dw/deleteCluster:
    post:
      summary: Deletes a cluster.
      description: Deletes a cluster.
      operationId: deleteCluster
      parameters:
        - name: input
          in: body
          required: true
          schema:
            $ref: '#/definitions/DeleteClusterRequest'
      responses:
        200:
          description: Expected response to a valid request.
          schema:
            $ref: '#/definitions/DeleteClusterResponse'
        default:
          description: The default response on an error.
          schema:
            $ref: '#/definitions/Error'
  /dw/listClusters:
    post:
      summary: Lists clusters.
      description: Lists clusters. If no cluster names are specified, the call lists all clusters.
      operationId: listClusters
      x-right: dw/listClusters
      x-paginates: true
      x-paging-default-max-items: 100
      parameters:
        - name: input
          in: body
          required: true
          schema:
            $ref: '#/definitions/ListClustersRequest'
      responses:
        200:
          description: Expected response to a valid request.
          schema:
            $ref: '#/definitions/ListClustersResponse'
        default:
          description: The default response on an error.
          schema:
            $ref: '#/definitions/Error'
  /dw/describeCluster:
    post:
      summary: Describe a cluster.
      description: Describe a cluster.
      operationId: describeCluster
      x-right: dw/describeCluster
      parameters:
        - name: input
          in: body
          required: true
          schema:
            $ref: '#/definitions/DescribeClusterRequest'
      responses:
        200:
          description: Expected response to a valid request.
          schema:
            $ref: '#/definitions/DescribeClusterResponse'
        default:
          description: The default response on an error.
          schema:
            $ref: '#/definitions/Error'
  /dw/updateCluster:
    post:
      summary: Update a cluster.
      description: Update a cluster.
      operationId: updateCluster
      x-right: dw/updateClusters
      parameters:
        - name: input
          in: body
          required: true
          schema:
            $ref: '#/definitions/UpdateClusterRequest'
      responses:
        200:
          description: Expected response to a valid request.
          schema:
            $ref: '#/definitions/UpdateClusterResponse'
        default:
          description: The default response on an error.
          schema:
            $ref: '#/definitions/Error'
definitions:
  Error:
    type: object
    description: An object returned on an error.
    properties:
      code:
        type: string
        description: The error code.
      message:
        type: string
        description: The error message.
  ClusterSummary:
    type: object
    description: Information about a cluster.
    required:
      - clusterName
      - crn
      - creationDate
      - cdhVersion
      - workerCpuCores
      - workerMemoryInGib
      - workerReplicas
      - workerReplicasOnline
      - workerAutoResize
      - status
    properties:
      clusterName:
        type: string
        description: The name of the cluster.
      crn:
        type: string
        description: The CRN of the cluster.
      creationDate:
        type: string
        format: date-time
        description: The date when the cluster was created.
      status:
        $ref: '#/definitions/ClusterStatus'
        description: The status of the cluster.
      cdhVersion:
        type: string
        description: The CDH version for the cluster.
      workerCpuCores:
        type: integer
        format: int32
        description: CPU cores per worker.
      workerMemoryInGib:
        type: integer
        format: int32
        description: Memory in GiB per worker.
      workerReplicas:
        type: integer
        format: int32
        description: Number of worker replicas.
      workerReplicasOnline:
        type: integer
        format: int32
        description: Number of worker replicas currently online.
      workerAutoResize:
        type: boolean
        description: If the number of worker replicas is auto scaling.
  Cluster:
    type: object
    description: Information about a cluster.
    required:
      - clusterName
      - crn
      - creationDate
      - cdhVersion
      - workerCpuCores
      - workerMemoryInGib
      - workerReplicas
      - workerReplicasOnline
      - workerAutoResize
      - status
    properties:
      clusterName:
        type: string
        description: The name of the cluster.
      crn:
        type: string
        description: The CRN of the cluster.
      creationDate:
        type: string
        format: date-time
        description: The date when the cluster was created.
      status:
        $ref: '#/definitions/ClusterStatus'
        description: The status of the cluster.
      cdhVersion:
        type: string
        description: The CDH version for the cluster.
      workerCpuCores:
        type: integer
        format: int32
        description: CPU cores per worker.
      workerMemoryInGib:
        type: integer
        format: int32
        description: Memory in GiB per worker.
      workerReplicas:
        type: integer
        format: int32
        description: Number of worker replicas.
      workerReplicasOnline:
        type: integer
        format: int32
        description: Number of worker replicas currently online.
      workerAutoResize:
        type: boolean
        description: If the number of worker replicas is auto scaling.
      coordinatorEndpoint:
        $ref: '#/definitions/Endpoint'
        description: The connection endpoint for the cluster coordinator.
      adminEndpoint:
        $ref: '#/definitions/Endpoint'
        description: The connection endpoint for the cluster administration UI.
  Endpoint:
    type: object
    description: A network endpoint that has both a public and a private hostname or IP address.
    required:
      - privateHost
      - publicHost
      - port
    properties:
      privateHost:
        type: string
        description: A private IP address or hostname. This is only accessible from within the pod network.
      publicHost:
        type: string
        description: A public IP address or hostname. This is routable from external services.
      port:
        type: integer
        format: int32
        description: A port.
  ClusterStatus:
    type: string
    description: The status of a cluster.
    enum:
      - STARTING
      - ONLINE
      - SCALING_UP
      - SCALING_DOWN
      - TERMINATING
      - STOPPED
      - FAILED
  CreateClusterRequest:
    type: object
    description: Request object for a create cluster request.
    required:
      - clusterName
    properties:
      clusterName:
        type: string
        description: The name of the cluster. This name must be unique, must have a maximum of 128 characters, and must contain only alphanumeric characters and hyphens. Names are case-sensitive.
      cdhVersion:
        type: string
        description: The CDH version.
      workerCpuCores:
        type: integer
        format: int32
        description: CPU cores per worker.
      workerMemoryInGib:
        type: integer
        format: int32
        description: Memory in GiB per worker.
      workerReplicas:
        type: integer
        format: int32
        description: Number of worker replicas.
  CreateClusterResponse:
    type: object
    description: Response object for a create cluster request.
    required:
      - cluster
    properties:
      cluster:
        $ref: '#/definitions/Cluster'
        description: The cluster that was created.
  UpdateClusterRequest:
    type: object
    description: Request object for an update cluster request.
    required:
      - clusterName
    properties:
      clusterName:
        type: string
        description: The name of the cluster. This name must be unique, must have a maximum of 128 characters, and must contain only alphanumeric characters and hyphens. Names are case-sensitive.
      cdhVersion:
        type: string
        description: The CDH version.
      workerCpuCores:
        type: integer
        format: int32
        description: CPU cores per worker.
      workerMemoryInGib:
        type: integer
        format: int32
        description: Memory in GiB per worker.
      workerReplicas:
        type: integer
        format: int32
        description: Number of worker replicas.
      updateClusterAutoResizeChanged:
        type: boolean
        description: If we change the worker autoscaling policy.
      updateClusterAutoResize:
        type: boolean
        description: If the autoscaling was turned off or on.
      updateClusterAutoResizeMax:
        type: integer
        format: int32
        description: Max number of replica when autoscaling if on.
      updateClusterAutoResizeMin:
        type: integer
        format: int32
        description: Max number of replica when autoscaling if on (optional).
      updateClusterAutoResizeCpu:
        type: integer
        format: int32
        description: CPU integer % (e.g. 80) when autoscaling if on (optional).
  UpdateClusterResponse:
    type: object
    description: Response object for an update cluster request.
    required:
      - cluster
    properties:
      cluster:
        $ref: '#/definitions/Cluster'
        description: The cluster that was updated.
  DeleteClusterRequest:
    type: object
    description: Request object for a delete cluster request.
    required:
      - clusterName
    properties:
      clusterName:
        type: string
        description: The name or CRN of the cluster.
  DeleteClusterResponse:
    type: object
    description: Response object for a delete cluster request.
  ListClustersRequest:
    type: object
    description: Request object for a list clusters request.
    properties:
      clusterNames:
        type: array
        items:
          type: string
        description: The names or CRNs of the clusters.
      pageSize:
        type: integer
        format: int32
        minimum: 1
        maximum: 100
        x-paging-page-size: true
        description: The size of each page.
      startingToken:
        type: string
        x-paging-input-token: true
        description: A token to specify where to start paginating. This is the nextToken from a previously truncated response.
  ListClustersResponse:
    type: object
    description: Response object for a list clusters request.
    required:
      - clusters
    properties:
      clusters:
        type: array
        items:
          $ref: '#/definitions/ClusterSummary'
        x-paging-result: true
        description: The clusters.
      nextToken:
        type: string
        x-paging-output-token: true
        description: The token to use when requesting the next set of results. If not present, there are no additional results.
  DescribeClusterRequest:
    type: object
    description: Request object for a describe cluster request.
    required:
      - clusterName
    properties:
      clusterName:
        type: string
        description: The name or CRN of the cluster.
  DescribeClusterResponse:
    type: object
    description: Response object for a describe cluster request.
    required:
      - cluster
    properties:
      cluster:
        $ref: '#/definitions/Cluster'
        description: The cluster.