# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      # - image: circleci/python:3.6.1
      - image: gethue/hue:latest

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: refresh sources
          command: |
            ls
  commit:
    docker:
      # - image: gethue/hue:latest
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "8c:68:29:28:04:80:38:31:c0:59:d9:3d:65:3e:b7:8c"

      - run:
          name: push to master
          command: |
            # cd ~/repo
            # Add [skip ci]
            git push origin HEAD:testing-romain2 -f

      # Run tests
      # - run:
      #     name: run python API tests
      #     command: |
      #       cd /usr/share/hue
      #       ./build/env/bin/hue test unit --with-xunit --with-cover

      # - run:
      #     name: run js tests
      #     command: |
      #       cd /usr/share/hue
      #       npm run test

      # # Code analyses
      # - run:
      #     name: run js tests
      #     command: |
      #       cd /usr/share/hue
      #       npm run lint

workflows:
  version: 2
  test-commit:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
                - /testing-romain2.*/ # TODO remove
      - commit:
          requires:
            - build
          filters:
            branches:
              only:
                - /.*testing.*/ # TODO remove
                - /.*commit.*/

# workflows:
#   version: 2
#   build-deploy:
#     jobs:
#       - build:
#           filters:
#             branches:
#               ignore:
#                 - develop
#                 - /feature-.*/
#       - deploy-stage:
#           requires:
#             - build
#           filters:
#             branches:
#               only: staging
